name: teste call
on: workflow_dispatch

jobs:
  teste:
    name: teste
    runs-on: ubuntu-latest
    steps:
      - name: echo
        uses: opluan/curriculum/.github/workflows/gha_test_call.yaml@main
